### ISSUE TITLE
initial bootstrap fails with int value

### ISSUE THREAD

**Issue by PI-Victor** [kubic-project/velum#117]
bootstraping a new cluster will fail if any of the fields in the `Initial CaaSP configuration` section is a single int.

![screenshot at 2017-04-13 13-54-23](https://cloud.githubusercontent.com/assets/6294120/25003677/f3919716-2050-11e7-9f7f-f8025d31db2b.png)

```
vpalade:terraform-1$ docker logs -f k8s_salt-minion-ca_velum-public-127.0.0.1_default_035a4bf0fee4f89e6cbea2f67f0ecbaf_0                                                                                   [67/504]
..................................++
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
.........................++
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1653, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 432, in certificate_managed
    new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1167, in create_certificate
    setattr(subject, entry, kwargs[entry])
  File "/usr/lib64/python2.7/site-packages/M2Crypto/X509.py", line 260, in __setattr__
    return m2.x509_name_set_by_nid(self.x509_name, self.nid[attr], value)
TypeError: expected string or Unicode object, int found
```

**Comment by mssola** [comment]
Fixed with #165
